# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Jesse Grushack
tagline:          'Random thoughts '
description:      'Random thoughts about Music, Ethereum, Bitcoin, etc..'
url:              google.com
baseurl:          

author:
  name:           'Jesse Grushack'
  url:            https://twitter.com/jessegrushack

paginate:         5

# Custom vars

version:         1.0

github:
  repo:           https://github.com/jgrushack

instagram:        https://instagram.com/jgrushack/

linkedin:         https://instagram.com/jgrushack/
twitter:          https://twitter.com/jessegrushack
