# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Jesse Grushack
tagline:          'Random thoughts '
description:      'Random thoughts about my work at <a href="http://www.byteacademy.co">Byte Academy</a>, Crypto Currencies, Music, etc.'
url:              google.com
baseurl:          /

author:
  name:           'Jesse Grushack'
  url:            https://twitter.com/jessegrushack

paginate:         5

# Custom vars


github:
  repo:           https://github.com/jgrushack
