# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Jesse Grushack
tagline:          'Random thoughts '
description:      ''
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Jesse Grushack'
  url:            https://twitter.com/jessegrushack

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
